name: coverage

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: nightly
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        run: >
          curl -LsSf 'https://github.com/taiki-e/cargo-llvm-cov/releases/download/v0.5.23/cargo-llvm-cov-x86_64-unknown-linux-musl.tar.gz'
          | tar xzf -
          && mv cargo-llvm-cov $HOME/.cargo/bin

      - name: Run cargo-llvm-cov
        run: cargo llvm-cov --doctests --all --all-features --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./
          fail_ci_if_error: false
          files: ./lcov.info
          verbose: true
