name: github pages

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build mdbook
        run: cargo install mdbook

      - name: Build cargo-readme
        run: cargo install cargo-readme

      - name: Build README.md
        run: cargo readme > README.md

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book
